/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NndsAlert {
        /**
          * How large should the button be?
         */
        "size"?: "small" | "medium" | "large";
        /**
          * What type of button is this?
         */
        "variant"?: "info" | "danger" | "success";
    }
    interface NndsButton {
        /**
          * Is the button full width?
         */
        "block"?: boolean;
        /**
          * Is the button disabled?
         */
        "disabled"?: boolean;
        /**
          * How large should the button be?
         */
        "size"?: "small" | "medium" | "large";
        /**
          * What type of button is this?
         */
        "type"?: "button" | "submit" | "reset";
        /**
          * What variant to use?
         */
        "variant"?: | "primary"
    | "secondary"
    | "tertiary"
    | "danger"
    | "success"
    | "link";
    }
}
declare global {
    interface HTMLNndsAlertElement extends Components.NndsAlert, HTMLStencilElement {
    }
    var HTMLNndsAlertElement: {
        prototype: HTMLNndsAlertElement;
        new (): HTMLNndsAlertElement;
    };
    interface HTMLNndsButtonElement extends Components.NndsButton, HTMLStencilElement {
    }
    var HTMLNndsButtonElement: {
        prototype: HTMLNndsButtonElement;
        new (): HTMLNndsButtonElement;
    };
    interface HTMLElementTagNameMap {
        "nnds-alert": HTMLNndsAlertElement;
        "nnds-button": HTMLNndsButtonElement;
    }
}
declare namespace LocalJSX {
    interface NndsAlert {
        /**
          * How large should the button be?
         */
        "size"?: "small" | "medium" | "large";
        /**
          * What type of button is this?
         */
        "variant"?: "info" | "danger" | "success";
    }
    interface NndsButton {
        /**
          * Is the button full width?
         */
        "block"?: boolean;
        /**
          * Is the button disabled?
         */
        "disabled"?: boolean;
        /**
          * How large should the button be?
         */
        "size"?: "small" | "medium" | "large";
        /**
          * What type of button is this?
         */
        "type"?: "button" | "submit" | "reset";
        /**
          * What variant to use?
         */
        "variant"?: | "primary"
    | "secondary"
    | "tertiary"
    | "danger"
    | "success"
    | "link";
    }
    interface IntrinsicElements {
        "nnds-alert": NndsAlert;
        "nnds-button": NndsButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nnds-alert": LocalJSX.NndsAlert & JSXBase.HTMLAttributes<HTMLNndsAlertElement>;
            "nnds-button": LocalJSX.NndsButton & JSXBase.HTMLAttributes<HTMLNndsButtonElement>;
        }
    }
}
